services:
  # Frontend React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - spring-boot-app-primary
    restart: unless-stopped

  # MySQL database
  mysql:
    image: mysql:8.3
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped


  # NGINX RTMP Server
  nginx-rtmp-server:
    build:
      context: ./nginx-rtmp
      dockerfile: Dockerfile
    image: nginx-rtmp-server:latest
    ports:
      - "1935:1935"
      - "9090:9090"
    volumes:
      - ./nginx-rtmp/html:/usr/share/nginx/html
    depends_on:
      - spring-boot-app-primary
    restart: unless-stopped

  # Spring Boot Application - Primary Replica
  spring-boot-app-primary:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: spring-boot-app-primary
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myappdb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      FAULT_RECOVERY_REPLICA_URLS: "http://spring-boot-app-primary:8080/health,http://spring-boot-app-secondary:8080/health"
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Spring Boot Application - Secondary Replica
  spring-boot-app-secondary:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: spring-boot-app-secondary
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myappdb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      FAULT_RECOVERY_REPLICA_URLS: "http://spring-boot-app-primary:8080/health,http://spring-boot-app-secondary:8080/health"
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


volumes:
  mysql_data:
