version: '3.8'

services:
  # MySQL database
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "myuser", "-pmypassword"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - backend

  # NGINX RTMP Server
  nginx-rtmp-server:
    image: nginx-rtmp-server:latest
    ports:
      - "1935:1935"
      - "9090:9090"
    volumes:
      - rtmp_data:/shared
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      resources:
        limits:
          cpus: '0.5'
          memory: '15MiB'
    networks:
      - frontend
      - backend

  # Spring Boot Application
  spring-boot-app:
    image: spring-boot-app:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/myappdb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: '400MiB'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/"]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 60s
    networks:
      - frontend
      - backend

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8001:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      update_config:
        failure_action: rollback

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

volumes:
  mysql_data:
    driver: local
  rtmp_data:
    driver: local